### ISSUE TITLE
How to link api to cloudfront?

### ISSUE THREAD

**Issue by ManotLuijiu** [skriems/next-material-aws-lambda#3]
npm run deploy is success, it is showing "Distribution Domain Name d3oug0bvoc946i.cloudfront.net" but I don't know how to get this to cloudfront.

**Comment by skriems** [comment]
@ManotLuijiu did you create your domain with `serverless create_domain` (iirc) ?

**Comment by skriems** [comment]
@ManotLuijiu I assume the above step was missing? Otherwise could you please elaborate a bit more on your issue?
